version: '2'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "superPassword_"
      MYSQL_DATABASE: "devDb"
  dummyserver:
    image: test/dummyserver:latest
    ports:
      - "8080:3000"
    depends_on: 
      - "db"